global using DentallApp.Features.Chatbot;
global using DentallApp.Features.Chatbot.DirectLine;
global using DentallApp.Features.Chatbot.DirectLine.Services;
global using DentallApp.Features.Chatbot.Dialogs;
global using DentallApp.Features.Chatbot.Factories;
global using DentallApp.Features.Chatbot.Helpers;
global using DentallApp.Features.Chatbot.Models;
global using DentallApp.Features.Chatbot.Handlers;
global using DentallApp.Features.Chatbot.Extensions;
global using DentallApp.Features.Chatbot.Configuration;
global using DentallApp.Features.GeneralTreatments;
global using DentallApp.Features.GeneralTreatments.DTOs;
global using DentallApp.Features.SpecificTreatments;
global using DentallApp.Features.SpecificTreatments.DTOs;
global using DentallApp.Features.ProformaInvoice;
global using DentallApp.Features.Genders;
global using DentallApp.Features.Users;
global using DentallApp.Features.Kinships;
global using DentallApp.Features.Roles;
global using DentallApp.Features.SecurityToken;
global using DentallApp.Features.SecurityToken.DTOs;
global using DentallApp.Features.EmailSending;
global using DentallApp.Features.Employees;
global using DentallApp.Features.Employees.Roles;
global using DentallApp.Features.Employees.Specialties;
global using DentallApp.Features.Appointments;
global using DentallApp.Features.AppointmentStatuses;
global using DentallApp.Features.AppointmentCancellation;
global using DentallApp.Features.AppointmentCancellation.DTOs;
global using DentallApp.Features.AvailabilityHours;
global using DentallApp.Features.AvailabilityHours.Models;
global using DentallApp.Features.EmployeeSchedules;
global using DentallApp.Features.EmployeeSchedules.DTOs;
global using DentallApp.Features.WeekDays;
global using DentallApp.Features.AppointmentReminders;
global using DentallApp.Features.PublicHolidays.Offices;

global using DentallApp.Middlewares;
global using DentallApp.Configuration;
global using DentallApp.DataAccess;
global using DentallApp.DataAccess.Repositories;
global using DentallApp.DataAccess.UnitOfWork;
global using DentallApp.DataAccess.DbConnectors;
global using DentallApp.DataAccess.DbTransactions;
global using DentallApp.DataAccess.SeedsData;
global using DentallApp.Entities;
global using DentallApp.Entities.BaseClasses;
global using DentallApp.Entities.Interfaces;
global using DentallApp.Attributes;
global using DentallApp.Helpers;
global using DentallApp.Helpers.HtmlConverterHelpers;
global using DentallApp.Helpers.TemplateEngineHelpers;
global using DentallApp.Helpers.DateTimeHelpers;
global using DentallApp.Helpers.InstantMessaging;
global using DentallApp.Helpers.PasswordHasher;
global using DentallApp.Responses;
global using Response = DentallApp.Responses.Response;
global using DentallApp.Extensions;
global using DentallApp.Constants;
global using static DentallApp.Constants.ResponseMessages;
global using static DentallApp.Constants.MessageTemplates;

global using System.Globalization;
global using System.Net;
global using System.Data;
global using System.Text;
global using System.Net.Mime;
global using System.Text.Encodings.Web;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using System.IdentityModel.Tokens.Jwt;

global using Microsoft.Bot.Builder;
global using Microsoft.Bot.Builder.Integration.AspNet.Core;
global using Microsoft.Bot.Builder.Dialogs;
global using Microsoft.Bot.Builder.TraceExtensions;
global using Microsoft.Bot.Schema;
global using Microsoft.Bot.Connector.Authentication;
global using AdaptiveCards;

global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Diagnostics;

global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.OpenApi.Models;
global using Microsoft.Extensions.Options;

global using Newtonsoft.Json.Linq;
global using Newtonsoft.Json;

global using DotEnv.Core;
global using Dapper;
global using Scrutor;

global using SendGrid;
global using SendGrid.Helpers.Mail;
global using SendGrid.Extensions.DependencyInjection;

global using EntityFramework.Exceptions.Common;
global using EntityFramework.Exceptions.MySQL.Pomelo;
global using DelegateDecompiler;
global using FileTypeChecker;
global using FileTypeChecker.Extensions;
global using iText.Html2pdf;
global using Scriban;
global using Quartz;
